setting asax scratch directory
 
============================================================
=====         Summary of your script job               =====
============================================================
  The script file is: src/batch.sh
  The time limit is 360:00:00 HH:MM:SS.
  The target directory is: /home/aubclsd0286/MP2
  The working directory is:  /scratch-local/aubclsd0286.32coreTorch.213065.asax-pbs1
  The memory limit is: 500gb
  The job will start running after: 202411190856.16
  Job Name: 32coreTorch
  Queue: -q bigmem
  Constraints: 
  Using  32  cores on master node  asax034.asc.edu
  Node list:  asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu asax034.asc.edu
  Cores:  32
  Command typed:
/scripts/run_script src/batch.sh     
  Queue submit command:
qsub -q bigmem -j oe -N 32coreTorch -a 202411190856.16 -r n -M wmh0011@auburn.edu -l walltime=360:00:00 -l select=ncpus=32:mpiprocs=32:mem=500000mb 

  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
6-31g benzene
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
6-31g dinitrogen
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
6-31g h_peroxide
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
6-31g pyrrole
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
6-31g water
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVDZ benzene
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVDZ dinitrogen
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVDZ h_peroxide
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVDZ pyrrole
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVDZ water
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVTZ benzene
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVTZ dinitrogen
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVTZ h_peroxide
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVTZ pyrrole
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVTZ water
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVQZ benzene
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVQZ dinitrogen
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVQZ h_peroxide
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVQZ pyrrole
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)


  Memory set to 447.035 GiB by Python driver.
PSIO_ERROR: unit = 35, errval = 5
Using device: cpu
cc-PVQZ water
Traceback (most recent call last):
  File "/home/aubclsd0286/MP2/src/mp2_torch.py", line 58, in <module>
    scf_e, scf_wfn = psi4.energy('scf', return_wfn=True)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/driver.py", line 501, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 2455, in run_scf
    scf_wfn = scf_helper(name, post_scf=False, **kwargs)
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/proc.py", line 1670, in scf_helper
    e_scf = scf_wfn.compute_energy()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 83, in scf_compute_energy
    self.initialize()
  File "/home/aubclsd0286/.conda/envs/mp2/lib/python3.9/site-packages/psi4/driver/procrouting/scf_proc/scf_iterator.py", line 197, in scf_initialize
    self.form_H()
RuntimeError: 
Fatal Error: PSIO_ERROR: 5 (open call failed)

 Check the location of your scratch directory which can be
 specified via the $PSI_SCRATCH environment variable.
 A local (non-network) scratch disk is strongly preferred.

 Please note that the scratch directory must exist, be
 writable by Psi4, and have available space.

Error occurred in file: /scratch/psilocaluser/conda-builds/psi4-multiout_1657298395608/work/psi4/src/psi4/libpsio/error.cc on line: 133
The most recent 5 function calls were:

psi::PSIO::open(unsigned long, int)

